"""Add CustomerStatus, ProjectStatus and ActivityStatus tables

Revision ID: c38d266facd8
Revises: b7cdadd5ce0e
Create Date: 2024-09-12 18:45:34.290308

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c38d266facd8"
down_revision: Union[str, None] = "b7cdadd5ce0e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Seed de dados
    op.execute(
        """
        INSERT INTO CustomerStatus (enumerator) VALUES
        ('active'),
        ('inactive'),
        ('suspended');

        """
    )

    op.execute(
        """
        INSERT INTO ProjectStatus (enumerator) VALUES
        ('open'),
        ('closed');
        """
    )

    op.execute(
        """
        INSERT INTO ActivityStatus (enumerator) VALUES
        ('not_started'),
        ('in_progress'),
        ('completed'),
        ('blocked');
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
